/* ════════════════════════════════════════════════════════════════
   미국 수학 커리큘럼 — 단일 출처(single source of truth)
   출처: 은우가 정리한 노션 "US Math Curriculum"(Khan Academy·enVision·Savvas 교재 기준)
   구조: curriculum.js(한국)와 동일 — LEVELS_US[] → subjects[] → chapters[{name, topics[]}]
   Grade 8~11은 학년별 필수 1과목, Grade 12+는 심화 선택 5과목(택1 이상)
════════════════════════════════════════════════════════════════ */

/* ── Grade 8: Pre-Algebra ── */
const PREALG=[
  {name:"Real Numbers",topics:["Rational Numbers as Decimals (converting repeating decimals to fractions)","Understanding Irrational Numbers","Comparing and Ordering Real Numbers","Evaluating Square Roots and Cube Roots","Solving Equations Using Square Roots and Cube Roots (e.g., x^2 = 49)","Laws of Integer Exponents (product, quotient, and power rules)","Scientific Notation (writing, comparing, and performing operations with very large or small numbers)"]},
  {name:"Analyze and Solve Linear Equations",topics:["Combining Like Terms to Solve Equations","Solving Equations with Variables on Both Sides","Solving Multi-Step Equations (using the distributive property)","Equations with No Solutions or Infinitely Many Solutions","Comparing Proportional Relationships (graphs vs. tables)","Connecting Proportional Relationships and Slope","Analyzing Linear Equations using y = mx and y = mx + b"]},
  {name:"Use Functions to Model Relationships",topics:["Understanding Relations and Functions (domain, range, and mapping diagrams)","Connecting Representations of Functions","Comparing Linear and Nonlinear Functions","Constructing Functions to Model Linear Relationships","Analyzing Functions Graphically (intervals of increase and decrease)"]},
  {name:"Investigate Bivariate Data",topics:["Constructing and Interpreting Scatter Plots","Analyzing Linear Associations (positive, negative, or no correlation)","Using Linear Models (Lines of Best Fit) to Make Predictions","Interpreting Two-Way Frequency and Relative Frequency Tables"]},
  {name:"Analyze and Solve Systems of Linear Equations",topics:["Estimating Solutions of Systems by Graphing (finding the intersection point)","Solving Systems of Equations Algebraically (Introductory Substitution and Elimination)","Determining the Number of Solutions to a System"]},
  {name:"Congruence and Similarity (Transformational Geometry)",topics:["Analyzing Rigid Transformations (Translations, Reflections, and Rotations)","Composing Transformations (performing multiple movements in a row)","Understanding Congruent and Similar Figures","Angles, Lines, and Transversals (Parallel lines cut by a transversal line)","Interior and Exterior Angles of Triangles"]},
  {name:"Understand and Apply the Pythagorean Theorem",topics:["Understanding the Pythagorean Theorem (a^2 + b^2 = c^2)","Understanding the Converse of the Pythagorean Theorem (proving if a triangle is a right triangle)","Applying the Theorem to Real-World Problems","Finding Distance in the Coordinate Plane between two points"]},
  {name:"Solve Problems Involving Surface Area and Volume",topics:["Finding the Surface Area of Three-Dimensional Figures","Finding the Volume of Cylinders","Finding the Volume of Cones","Finding the Volume of Spheres"]},
];

/* ── Grade 9: Algebra 1 ── */
const ALG1=[
  {name:"Solving Equations and Inequalities",topics:["Operations on Real Numbers (rational and irrational behavior)","Solving Linear Equations","Solving Equations with a Variable on Each Side","Literal Equations and Formulas (rearranging variables)","Solving and Graphing Inequalities in One Variable","Compound Inequalities","Absolute Value Equations and Inequalities"]},
  {name:"Linear Equations",topics:["Slope-Intercept Form (y = mx + b)","Point-Slope Form (y - y1 = m(x - x1))","Standard Form (Ax + By = C)","Parallel and Perpendicular Lines"]},
  {name:"Linear Functions",topics:["Relations and Functions (domain, range, vertical line test)","Linear Functions (identifying, evaluating, graphing, and writing)","Transforming Linear Functions (shifting and stretching graphs)","Arithmetic Sequences","Scatter Plots and Lines of Fit","Analyzing Lines of Fit (linear regression)"]},
  {name:"Systems of Linear Equations and Inequalities",topics:["Solving Systems of Equations by Graphing","Solving Systems of Equations by Substitution","Solving Systems of Equations by Elimination","Linear Inequalities in Two Variables","Systems of Linear Inequalities"]},
  {name:"Piecewise Functions",topics:["Absolute Value Functions","Piecewise-Defined Functions","Step Functions (greatest integer functions)","Transformations of Piecewise-Defined Functions"]},
  {name:"Exponents and Exponential Functions",topics:["Rational Exponents and Properties of Exponents","Exponential Functions","Exponential Growth and Decay","Geometric Sequences","Transformations of Exponential Functions"]},
  {name:"Polynomials and Factoring",topics:["Adding and Subtracting Polynomials","Multiplying Polynomials (FOIL method)","Multiplying Special Cases (perfect square trinomials, difference of squares)","Factoring Polynomials (Greatest Common Factor / GCF)","Factoring x^2 + bx + c","Factoring ax^2 + bx + c"]},
  {name:"Quadratic Functions",topics:["Key Features of Graphs of Quadratic Functions","Quadratic Functions in Vertex Form (y = a(x-h)^2 + k)","Quadratic Functions in Standard Form","Modeling with Quadratic Functions","Comparing Linear, Exponential, and Quadratic Models"]},
  {name:"Solving Quadratic Equations",topics:["Solving Quadratic Equations Using Graphs and Tables","Solving Quadratic Equations by Factoring","Rewriting Radical Expressions (simplifying square roots)","Solving Quadratic Equations Using Square Roots","Completing the Square","The Quadratic Formula (x = (-b ± sqrt(b^2 - 4ac)) / 2a)"]},
  {name:"Working with Functions",topics:["The Square Root Function","The Cube Root Function","Analyzing Functions Graphically","Translations of Functions","Compressions, Stretches, and Reflections of Functions","Operations with Functions (adding, subtracting, multiplying functions)","Inverse Functions"]},
  {name:"Statistics",topics:["Analyzing Data Distributions","Standard Deviation","Two-Way Frequency Tables","Correlation and Causation"]},
];

/* ── Grade 10: Geometry ── */
const GEOM=[
  {name:"Foundations of Geometry",topics:["Points, Lines, and Planes","Measuring Segments and Angles","Exploring Angle Pairs","Basic Geometric Constructions","Midpoint and Distance in the Coordinate Plane"]},
  {name:"Parallel and Perpendicular Lines",topics:["Lines and Angles","Properties of Parallel Lines (Transversals)","Proving Lines Parallel","Parallel and Perpendicular Lines in the Coordinate Plane","Equations of Lines in the Coordinate Plane"]},
  {name:"Transformations",topics:["Translations","Reflections","Rotations","Symmetry","Dilations","Compositions of Transformations"]},
  {name:"Triangle Congruence",topics:["Congruent Figures","Proving Triangles Congruent: SSS and SAS","Proving Triangles Congruent: ASA and AAS","Corresponding Parts of Congruent Triangles (CPCTC)","Isosceles and Equilateral Triangles","Congruence in Right Triangles (HL)"]},
  {name:"Relationships in Triangles",topics:["Midsegments of Triangles","Perpendicular and Angle Bisectors","Bisectors in Triangles (Circumcenter and Incenter)","Medians and Altitudes (Centroid and Orthocenter)","Indirect Proof","Inequalities in One Triangle"]},
  {name:"Quadrilaterals and Other Polygons",topics:["The Polygon Angle-Sum Theorems","Properties of Parallelograms","Proving That a Quadrilateral Is a Parallelogram","Properties of Special Parallelograms (Rhombuses, Rectangles, Squares)","Conditions for Special Parallelograms","Properties of Trapezoids and Kites"]},
  {name:"Similarity",topics:["Similar Polygons","Proving Triangles Similar (AA, SAS, SSS Similarity)","Similarity in Right Triangles","Proportionality Theorems"]},
  {name:"Right Triangles and Trigonometry",topics:["The Pythagorean Theorem and Its Converse","Special Right Triangles (30-60-90 and 45-45-90)","Trigonometric Ratios (Sine, Cosine, Tangent)","Angles of Elevation and Depression","The Law of Sines","The Law of Cosines"]},
  {name:"Coordinate Geometry",topics:["Polygons in the Coordinate Plane","Applying Coordinate Geometry","Proofs Using Coordinate Geometry","Partitioning a Segment"]},
  {name:"Circles",topics:["Tangent Lines","Chords and Arcs","Inscribed Angles","Angle Measures and Segment Lengths (Secants and Tangents)","Circles in the Coordinate Plane (Equation of a Circle)","Arc Length and Area of a Sector"]},
  {name:"Two- and Three-Dimensional Models (Area & Volume)",topics:["Areas of Parallelograms and Triangles","Areas of Trapezoids, Rhombuses, and Kites","Areas of Regular Polygons","Three-Dimensional Figures and Cross Sections","Volume of Prisms and Cylinders","Volume of Pyramids and Cones","Surface Area and Volume of Spheres"]},
  {name:"Probability",topics:["Experimental and Theoretical Probability","Geometric Probability","Permutations and Combinations","Compound Probability (Independent and Dependent Events)","Conditional Probability and Two-Way Tables"]},
];

/* ── Grade 11: Algebra 2 (enVision) ── */
const ALG2=[
  {name:"Linear Functions and Systems",topics:["Key Features of Linear Functions","Transformations of Linear Functions","Systems of Linear Equations in Three Variables","Solving Linear Inequalities and Systems of Inequalities","Piecewise-Defined and Step Functions"]},
  {name:"Quadratic Functions and Equations",topics:["Vertex Form of a Quadratic Function","Standard Form of a Quadratic Function","Complex Numbers (a + bi)","Factoring Quadratic Expressions","Completing the Square","The Quadratic Formula and the Discriminant","Quadratic Systems of Equations and Inequalities"]},
  {name:"Polynomial Functions",topics:["Graphing Polynomial Functions and End Behavior","Adding, Subtracting, and Multiplying Polynomials","Polynomial Division (Long Division and Synthetic Division)","The Remainder Theorem and Factor Theorem","The Fundamental Theorem of Algebra and Complex Roots"]},
  {name:"Rational Exponents and Radical Functions",topics:["nth Roots and Rational Exponents","Properties of Radicals and Exponents","Graphing Radical Functions","Solving Radical Equations","Function Operations and Composites"]},
  {name:"Exponential and Logarithmic Functions",topics:["Exponential Growth and Decay Functions","The Natural Base e and Continuous Growth","Logarithms and Logarithmic Functions","Properties of Logarithms (Product, Quotient, Power Rules)","Solving Exponential and Logarithmic Equations","Geometric Sequences and Series"]},
  {name:"Rational Functions",topics:["Inverse Variation and Joint Variation","Graphing Rational Functions (Asymptotes and Holes)","Multiplying and Dividing Rational Expressions","Adding and Subtracting Rational Expressions","Solving Rational Equations"]},
  {name:"Trigonometric Functions",topics:["Angles, Radian Measure, and the Unit Circle","The Sine and Cosine Functions","The Tangent Function","Sinusoidal Graph Transformations (Midline, Amplitude, Period)","Modeling with Sinusoidal Functions"]},
  {name:"Trigonometric Identities and Equations",topics:["Basic Trigonometric Identities (Pythagorean, Reciprocal, Quotient)","Sum and Difference Identities","Double-Angle and Half-Angle Identities","Solving Trigonometric Equations"]},
  {name:"Conic Sections",topics:["Parabolas (Focus and Directrix)","Circles in the Coordinate Plane","Ellipses (Foci and Equations)","Hyperbolas (Asymptotes and Equations)"]},
  {name:"Matrices",topics:["Matrix Operations (Addition, Subtraction, Scalar Multiplication)","Multiplying Matrices","Determinants and Multiplicative Inverses of Matrices","Solving Systems of Equations Using Matrices"]},
  {name:"Data Analysis and Statistics",topics:["Statistical Questions and Sampling Methods","Normal Distributions (z-scores)","Margin of Error and Confidence Intervals","Analyzing and Designing Statistical Studies"]},
  {name:"Probability",topics:["Permutations and Combinations","Theoretical and Experimental Probability","Independent and Dependent Events","Conditional Probability and Two-Way Tables","Probability Distributions"]},
];

/* ── Grade 12+: Pre-calculus (Savvas) ── */
const PRECALC=[
  {name:"Prerequisites",topics:["Real Numbers","Cartesian Coordinate System","Linear Equations and Inequalities","Lines in the Plane","Solving Equations Graphically, Numerically, and Algebraically","Complex Numbers","Solving Inequalities Algebraically and Graphically"]},
  {name:"Functions and Graphs",topics:["Modeling and Equation Solving","Functions and Their Properties","Twelve Basic Functions","Building Functions from Functions","Parametric Relations and Inverses","Graphical Transformations","Modeling with Functions"]},
  {name:"Polynomial, Power, and Rational Functions",topics:["Linear and Quadratic Functions and Modeling","Modeling with Power Functions","Polynomial Functions of Higher Degree with Modeling","Real Zeros of Polynomial Functions","Complex Zeros and the Fundamental Theorem of Algebra","Graphs of Rational Functions","Solving Equations in One Variable","Solving Inequalities in One Variable"]},
  {name:"Exponential, Logistic, and Logarithmic Functions",topics:["Exponential and Logistic Functions","Exponential and Logistic Modeling","Logarithmic Functions and Their Graphs","Properties of Logarithmic Functions","Equation Solving and Modeling","Mathematics of Finance"]},
  {name:"Trigonometric Functions",topics:["Angles and Their Measures","Trigonometric Functions of Acute Angles","Trigonometry Extended: The Circular Functions","Graphs of Sine and Cosine: Sinusoids","Graphs of Other Trigonometric Functions (Tangent, Cotangent, Secant, Cosecant)","Graphs of Composite Trigonometric Functions","Inverse Trigonometric Functions","Solving Problems with Trigonometry"]},
  {name:"Analytic Trigonometry",topics:["Fundamental Identities","Proving Trigonometric Identities","Sum and Difference Identities","Multiple-Angle Identities","The Law of Sines","The Law of Cosines"]},
  {name:"Applications of Trigonometry",topics:["Vectors in the Plane","Dot Product of Vectors","Parametric Equations and Motion","Polar Coordinates","Graphs of Polar Equations","De Moivre's Theorem and nth Roots"]},
  {name:"Systems and Matrices",topics:["Solving Systems of Two Equations","Matrix Algebra","Multivariate Linear Systems and Row Operations","Systems of Inequalities in Two Variables"]},
  {name:"Analytic Geometry in Two and Three Dimensions",topics:["Conic Sections and a New Look at Parabolas","Circles and Ellipses","Hyperbolas","Quadratic Equations with xy Terms","Polar Equations of Conics","Three-Dimensional Cartesian Coordinate System"]},
  {name:"Discrete Mathematics",topics:["Basic Combinatorics","Binomial Theorem","Sequences","Series","Mathematical Induction"]},
  {name:"Statistics and Probability",topics:["Probability","Statistics (Graphical)","Statistics (Numerical)","Random Variables and Probability Models","Statistical Literacy"]},
  {name:"An Introduction to Calculus: Limits, Derivatives, and Integrals",topics:["Limits and Motion: The Tangent Problem","Limits and Motion: The Area Problem","More on Limits","Numerical Derivatives and Integrals"]},
];

/* ── Grade 12+ 심화선택: Statistics & Probability (Khan Academy) ── */
const STATPROB=[
  {name:"Analyzing categorical data",topics:["Individuals, variables, and categorical & quantitative data","Read picture graphs (multi-step problems)","Create bar graphs","Read bar graphs (2-step problems)","Read two-way frequency tables","Create two-way frequency tables","Create two-way relative frequency tables","Analyze two-way frequency tables","Interpret two-way tables","Trends in categorical data","Identify marginal and conditional distributions","Marginal distributions","Conditional distributions"]},
  {name:"Displaying and comparing quantitative data",topics:["Creating frequency tables","Creating dot plots","Reading dot plots & frequency tables","Create histograms","Read histograms","Reading stem and leaf plots","Shape of distributions","Clusters, gaps, & peaks in data distributions","Comparing distributions","Comparing data displays","Comparing data distributions","Comparing center and spread"]},
  {name:"Summarizing quantitative data",topics:["Mean, median, and mode","Calculating the mean","Calculating the median","Calculating the mean: data displays","Calculating the median: data displays","Effects of shifting, adding, & removing a data point","Missing value given the mean","Median & range puzzlers","Interquartile range (IQR)","Standard deviation of a population","Variance","Sample and population standard deviation","Creating box plots","Reading box plots","Interpreting quartiles","Identifying outliers","Mean absolute deviation (MAD)"]},
  {name:"Modeling data distributions",topics:["Calculate percentiles","Calculating z-scores","Transforming data","Properties of density curves","Area under density curves","Empirical rule","Normal distribution: Area above or below a point","Normal distribution: Area between two points","Normal calculations in reverse"]},
  {name:"Exploring bivariate numerical data",topics:["Constructing scatter plots","Making appropriate scatter plots","Positive and negative linear associations from scatter plots","Describing trends in scatterplots","Correlation coefficient intuition","Eyeballing the line of best fit","Estimating equations of lines of best fit, and using them to make predictions","Estimating slope of line of best fit","Calculate and interpret residuals","Calculating the equation of the least-squares line","Interpreting slope and y-intercept for linear models","Residual plots","Effects of influential points"]},
  {name:"Study design",topics:["Statistical questions","Valid claims","Making inferences from random samples","Identify the population and sample","Using probability to make fair decisions","Simple random samples","Sampling methods","Types of statistical studies","Experiment designs"]},
  {name:"Probability",topics:["Simple probability","Comparing probabilities","Subsets of sample spaces","Basic set notation","Experimental probability","Making predictions with probability","Interpret results of simulations","Adding probabilities","Two-way tables, Venn diagrams, and probability","Sample spaces for compound events","Independent probability","Probabilities of compound events","Probability of \"at least one\" success","Dependent probability","Calculate conditional probability","Dependent and independent events"]},
  {name:"Counting, permutations, and combinations",topics:["The counting principle","Permutations","Combinations","Permutations & combinations with overcounting","Probability with permutations and combinations"]},
  {name:"Random variables",topics:["Constructing probability distributions","Probability models","Probability with discrete random variables","Expected value","Mean (expected value) of a discrete random variable","Standard deviation of a discrete random variable","Probability in density curves","Probability in normal density curves","Transforming random variables","Combining random variables","Combining normal random variables","Identifying binomial variables","Binomial probability formula","Calculating binomial probability","Mean and standard deviation of a binomial random variable","Binomial vs. geometric random variables","Geometric probability","Cumulative geometric probability","Expected value with empirical probabilities","Expected value with calculated probabilities","Making decisions with expected values"]},
  {name:"Sampling distributions",topics:["Biased and unbiased estimators","The normal condition for sample proportions","Mean and standard deviation of sample proportions","Finding probabilities with sample proportions","Mean and standard deviation of sample means","Sample means and the central limit theorem","Finding probabilities with sample means"]},
  {name:"Confidence intervals",topics:["Conditions for a z interval for a proportion","Finding the critical value z* for a desired confidence level","Calculating a z interval for a proportion","Sample size and margin of error in a z interval for p","Conditions for a t interval for a mean","Finding the critical value t* for a desired confidence level","Calculating a t interval for a mean","Sample size and margin of error in a confidence interval for a mean"]},
  {name:"Significance tests (hypothesis testing)",topics:["Simple hypothesis testing","Writing null and alternative hypotheses","Estimating P-values from simulations","Type I vs Type II error","Error probabilities and power","Writing hypotheses for a test about a proportion","Conditions for a z test about a proportion","Calculating the test statistic in a z test for a proportion","Calculating the P-value in a z test for a proportion","Making conclusions in a z test for a proportion","Writing hypotheses for a test about a mean","Conditions for a t test about a mean","Calculating the test statistic in a t test for a mean","Calculating the P-value in a t test for a mean","Making conclusions in a t test for a mean"]},
  {name:"Inference for categorical data (chi-square tests)",topics:["Expected counts in a goodness-of-fit test","Conditions for a goodness-of-fit test","Test statistic and P-value in a goodness-of-fit test","Conclusions in a goodness-of-fit test","Expected counts in chi-squared tests with two-way tables","Test statistic and P-value in chi-square tests with two-way tables","Making conclusions in chi-square tests for two-way tables"]},
];

/* ── Grade 12+ 심화선택: College Algebra (Khan Academy) ── */
const COLALG=[
  {name:"Linear equations and inequalities",topics:["Equations with parentheses","Equations with parentheses: decimals & fractions","Number of solutions to equations","Solutions to 2-variable equations","Interpret points relative to a system","Multi-step linear inequalities","Compound inequalities","Comparing linear rates word problems","Absolute value equations"]},
  {name:"Graphs and forms of linear equations",topics:["Intercepts from an equation","Slope from two points","Slope from equation","Graphing from slope","Horizontal & vertical lines","Slope-intercept intro","Graph from slope-intercept form","Point-slope form","Linear equations in any form","Parallel & perpendicular lines from equation","Write equations of parallel & perpendicular lines"]},
  {name:"Functions",topics:["Evaluate functions","Evaluate functions from their graph","Function inputs & outputs: equation","Function inputs & outputs: graph","Domain and range from graph","Determine the domain of functions","Recognize functions from tables","Recognize functions from graphs","Positive and negative intervals","Increasing and decreasing intervals","Evaluate inverse functions","Find inverses of linear functions"]},
  {name:"Quadratics: Multiplying and factoring",topics:["Multiply binomials","Multiply difference of squares","Multiply perfect squares of binomials","Factoring quadratics intro","Factor quadratics by grouping","Difference of squares","Perfect squares"]},
  {name:"Quadratic functions and equations",topics:["Quadratics by taking square roots","Graph quadratics in vertex form","Quadratics by factoring","Solve equations using structure","Quadratic formula","Completing the square (intro)","Solve equations by completing the square","Complete the square","Features of quadratic functions","Graph parabolas in all forms","Interpret quadratic models"]},
  {name:"Complex numbers",topics:["Simplify roots of negative numbers","Add & subtract complex numbers","Multiply complex numbers (basic)","Multiply complex numbers","Divide complex numbers"]},
  {name:"Exponents and radicals",topics:["Multiply & divide powers (integer exponents)","Powers of products & quotients (integer exponents)","Properties of exponents challenge (integer exponents)","Simplify square-root expressions","Interpret exponential expressions word problems","Graphing exponential growth & decay"]},
  {name:"Rational expressions and equations",topics:["Rational equations","Find inverses of rational functions","Mixtures and combined rates word problems","Reduce rational expressions to lowest terms","Multiply & divide rational expressions","Add & subtract rational expressions (basic)","Add & subtract rational expressions"]},
  {name:"Relating algebra and geometry",topics:["Distance between two points","Midpoint formula","Features of a circle from its standard equation","Graph a circle from its standard equation","Write standard equation of a circle","Features of a circle from its expanded equation","Graph a circle from its expanded equation"]},
  {name:"Polynomial arithmetic",topics:["Average rate of change of polynomials","Add polynomials (intro)","Subtract polynomials (intro)","Add & subtract polynomials","Factor polynomials: common factor","Factor higher degree polynomials","Factor polynomials using structure"]},
  {name:"Advanced function types",topics:["Shift absolute value graphs","Evaluate piecewise functions","Piecewise functions graphs","Evaluate composite functions","Find composite functions","Verify inverse functions"]},
  {name:"Transformations of functions",topics:["Shift functions","Reflect functions","Even and odd functions: Graphs and tables","Scale functions vertically"]},
  {name:"Rational exponents and radicals",topics:["Rational exponents challenge","Properties of exponents (rational exponents)","Evaluate radical expressions challenge","Solve exponential equations using exponent properties","Interpret change in exponential models","Square-root equations intro","Square-root equations"]},
  {name:"Logarithms",topics:["Evaluate logarithms","Evaluate logarithms (advanced)","Relationship between exponentials & logarithms","Use the properties of logarithms","Evaluate logarithms: change of base rule","Exponential model word problems"]},
];

/* ── Grade 12+ 심화선택: AP Calculus AB (Khan Academy) ── */
const APCALC_AB=[
  {name:"Limits and continuity",topics:["Limits intro","Estimating limit values from graphs","One-sided limits from graphs","Connecting limits and graphical behavior","Missing important function behavior, and functions with oscillating behavior","Creating tables for approximating limits","Estimating limits from tables","One-sided limits from tables","Limits of combined functions: sums and differences","Limits of combined functions: products and quotients","Limits of composite functions","Limits by direct substitution","Direct substitution with limits that don't exist","Limits of trigonometric functions","Limits of piecewise functions","Limits of piecewise functions: absolute value","Limits by factoring","Limits using conjugates","Limits using trig identities","Conclusions from direct substitution (finding limits)","Next steps after indeterminate form (finding limits)","Strategy in finding limits","Squeeze theorem","Classify discontinuities","Continuity at a point (graphical)","Continuity at a point (algebraic)","Continuity over an interval","Continuity and common functions","Removable discontinuities","Infinite limits: graphical","Infinite limits: algebraic","Limits at infinity: graphical","Limits at infinity of quotients","Limits at infinity of quotients with square roots","Using the intermediate value theorem","Justification with the intermediate value theorem"]},
  {name:"Differentiation: definition and basic derivative rules",topics:["Secant lines & average rate of change","Derivative as slope of curve","The derivative & tangent line equations","Derivative as a limit","Estimate derivatives","Differentiability at a point: graphical","Differentiability at a point: algebraic","Power rule (positive integer powers)","Power rule (negative & fractional powers)","Power rule (with rewriting the expression)","Basic derivative rules: find the error","Basic derivative rules: table","Differentiate polynomials","Differentiate integer powers (mixed positive and negative)","Tangents of polynomials","Derivatives of sin(x) and cos(x)","Derivatives of e^x and ln(x)","Disguised derivatives","Derivatives that help with finding limits","Differentiate products","Product rule with tables","Differentiate quotients","Quotient rule with tables","Differentiate rational functions","Derivatives of tan(x), cot(x), sec(x), and csc(x)"]},
  {name:"Differentiation: composite, implicit, and inverse functions",topics:["Identify composite functions","Chain rule intro","Chain rule with tables","Derivatives of a^x and log_a(x)","Chain rule capstone","Implicit differentiation","Derivatives of inverse functions","Derivatives of inverse trigonometric functions","Differentiating functions: Find the error","Manipulating functions before differentiation","Differentiating using multiple rules: strategy","Differentiating using multiple rules","Second derivatives","Second derivatives (implicit equations)"]},
  {name:"Contextual applications of differentiation",topics:["Interpreting the meaning of the derivative in context","Interpret motion graphs","Motion problems (differential calc)","Rates of change in other applied contexts (non-motion problems)","Analyzing related rates problems: expressions","Analyzing related rates problems: equations","Differentiate related functions","Related rates intro","Related rates (multiple rates)","Related rates (Pythagorean theorem)","Related rates (advanced)","Related rates with context","Approximation with local linearity","Linear approximations of rational functions","L'Hôpital's rule: 0/0","L'Hôpital's rule: ∞/∞"]},
  {name:"Analytical applications of differentiation",topics:["Using the mean value theorem","Justification with the mean value theorem","Find critical points","Increasing & decreasing intervals","Relative minima & maxima","Absolute minima & maxima (closed intervals)","Absolute minima & maxima (entire domain)","Concavity intro","Inflection points intro","Analyze concavity","Find inflection points","Second derivative test","Analyzing a function with its derivative","Justification using first derivative","Justification using second derivative","Connecting f, f', and f'' graphically","Optimization","Tangents to graphs of implicit relations","Analyze functions (calculator-active)"]},
  {name:"Integration and accumulation of change",topics:["Accumulation of change","Calculating net area using geometry","Left & right Riemann sums","Over- and under-estimation of Riemann sums","Midpoint & trapezoidal sums","Summation notation","Riemann sums in summation notation","Definite integral as the limit of a Riemann sum","Functions defined by definite integrals (accumulation functions)","Finding derivative with fundamental theorem of calculus","Finding derivative with fundamental theorem of calculus: chain rule","Interpreting the behavior of accumulation functions","Finding definite integrals using area formulas","Finding definite integrals using algebraic properties","Definite integrals over adjacent intervals","The fundamental theorem of calculus and definite integrals","Antiderivatives and indefinite integrals","Reverse power rule","Reverse power rule: negative and fractional powers","Reverse power rule: sums & multiples","Reverse power rule: rewriting before integrating","Indefinite integrals: e^x & 1/x","Indefinite integrals: sin & cos","Definite integrals: reverse power rule","Definite integrals: common functions","Definite integrals of piecewise functions","Definite integral of functions with removable or jump discontinuities","u-substitution: defining u","u-substitution: indefinite integrals","u-substitution: definite integrals","u-substitution: definite integral of exponential function","Integration using long division","Integration using completing the square"]},
  {name:"Differential equations",topics:["Write differential equations","Verify solutions to differential equations","Slope fields & equations","Reasoning using slope fields","Separable differential equations: find the error","Separable differential equations","Identify separable equations","Particular solutions to differential equations","Particular solutions to separable differential equations","Domain of particular solutions to differential equations","Differential equations: exponential model equations","Differential equations: exponential model word problems"]},
  {name:"Applications of integration",topics:["Average value of a function","Analyzing motion problems (integral calculus)","Motion problems (with integrals)","Interpreting definite integrals in context","Analyzing problems involving definite integrals","Problems involving definite integrals (algebraic)","Area between a curve and the x-axis","Area between two curves given end points","Area between two curves","Composite area between curves","Horizontal areas between curves","Area between curves that intersect at more than two points (calculator-active)","Volumes with cross sections: squares and rectangles (intro)","Volumes with cross sections: squares and rectangles","Volumes with cross sections: triangles and semicircles","Disc method: revolving around x- or y-axis","Disc method: revolving around other axes","Washer method: revolving around x- or y-axis","Washer method: revolving around other axes","Contextual and analytical applications of integration (calculator-active)"]},
];

/* ── Grade 12+ 심화선택: AP Calculus BC (Khan Academy, AB 8개 유닛 + BC 전용 2개) ── */
const APCALC_BC=[
  {name:"Limits and continuity",topics:["Limits intro","Estimating limit values from graphs","One-sided limits from graphs","Connecting limits and graphical behavior","Creating tables for approximating limits","Estimating limits from tables","One-sided limits from tables","Limits of combined functions: sums and differences","Limits of combined functions: products and quotients","Limits of composite functions","Limits by direct substitution","Direct substitution with limits that don't exist","Limits of trigonometric functions","Limits of piecewise functions","Limits by factoring","Limits using conjugates","Limits using trig identities","Conclusions from direct substitution (finding limits)","Next steps after indeterminate form (finding limits)","Strategy in finding limits","Squeeze theorem","Classify discontinuities","Continuity at a point (graphical)","Continuity at a point (algebraic)","Continuity over an interval","Continuity and common functions","Removable discontinuities","Infinite limits: graphical","Infinite limits: algebraic","Limits at infinity: graphical","Limits at infinity of quotients","Limits at infinity of quotients with square roots","Using the intermediate value theorem","Justification with the intermediate value theorem"]},
  {name:"Differentiation: definition and basic derivative rules",topics:["Secant lines & average rate of change","Derivative as slope of curve","The derivative & tangent line equations","Derivative as a limit","Estimate derivatives","Differentiability at a point: graphical","Differentiability at a point: algebraic","Power rule (positive integer powers)","Power rule (negative & fractional powers)","Power rule (with rewriting the expression)","Basic derivative rules: find the error","Basic derivative rules: table","Differentiate polynomials","Differentiate integer powers (mixed positive and negative)","Tangents of polynomials","Derivatives of sin(x) and cos(x)","Derivatives of e^x and ln(x)","Differentiate products","Product rule with tables","Differentiate quotients","Quotient rule with tables","Differentiate rational functions","Derivatives of tan(x), cot(x), sec(x), and csc(x)"]},
  {name:"Differentiation: composite, implicit, and inverse functions",topics:["Identify composite functions","Chain rule intro","Chain rule with tables","Derivatives of a^x and log_a(x)","Chain rule capstone","Implicit differentiation","Derivatives of inverse functions","Derivatives of inverse trigonometric functions","Differentiating functions: Find the error","Manipulating functions before differentiation","Differentiating using multiple rules: strategy","Differentiating using multiple rules","Second derivatives","Second derivatives (implicit equations)","Disguised derivatives"]},
  {name:"Contextual applications of differentiation",topics:["Interpreting the meaning of the derivative in context","Interpret motion graphs","Motion problems (differential calc)","Rates of change in other applied contexts (non-motion problems)","Analyzing related rates problems: expressions","Analyzing related rates problems: equations","Differentiate related functions","Related rates intro","Related rates (multiple rates)","Related rates (Pythagorean theorem)","Related rates (advanced)","Approximation with local linearity","L'Hopital's rule: 0/0","L'Hopital's rule: infinity/infinity"]},
  {name:"Applying derivatives to analyze functions",topics:["Using the mean value theorem","Justification with the mean value theorem","Find critical points","Increasing & decreasing intervals","Relative minima & maxima","Absolute minima & maxima (closed intervals)","Absolute minima & maxima (entire domain)","Concavity intro","Inflection points intro","Analyze concavity","Find inflection points","Second derivative test","Analyzing a function with its derivative","Justification using first derivative","Justification using second derivative","Connecting f, f', and f'' graphically","Optimization","Tangents to graphs of implicit relations","Analyze functions (calculator-active)"]},
  {name:"Integration and accumulation of change",topics:["Accumulation of change","Left & right Riemann sums","Over- and under-estimation of Riemann sums","Midpoint & trapezoidal sums","Summation notation","Riemann sums in summation notation","Definite integral as the limit of a Riemann sum","Functions defined by definite integrals (accumulation functions)","Finding derivative with fundamental theorem of calculus","Finding derivative with fundamental theorem of calculus: chain rule","Interpreting the behavior of accumulation functions","Finding definite integrals using area formulas","Finding definite integrals using algebraic properties","Definite integrals over adjacent intervals","The fundamental theorem of calculus and definite integrals","Antiderivatives and indefinite integrals","Reverse power rule","Reverse power rule: negative and fractional powers","Reverse power rule: sums & multiples","Reverse power rule: rewriting before integrating","Indefinite integrals: e^x & 1/x","Indefinite integrals: sin & cos","Definite integrals: reverse power rule","Definite integrals: common functions","Definite integrals of piecewise functions","u-substitution: defining u","u-substitution: indefinite integrals","u-substitution: definite integrals","Integration using long division","Integration using completing the square","Integration by parts","Integration by parts: definite integrals","Integration with partial fractions","Improper integrals"]},
  {name:"Differential equations",topics:["Write differential equations","Verify solutions to differential equations","Slope fields & equations","Reasoning using slope fields","Euler's method","Separable differential equations: find the error","Separable differential equations","Identify separable equations","Particular solutions to differential equations","Particular solutions to separable differential equations","Differential equations: exponential model equations","Differential equations: exponential model word problems","Differential equations: logistic model word problems"]},
  {name:"Applications of integration",topics:["Average value of a function","Analyzing motion problems (integral calculus)","Motion problems (with integrals)","Interpreting definite integrals in context","Analyzing problems involving definite integrals","Problems involving definite integrals (algebraic)","Area between a curve and the x-axis","Area between two curves given end points","Area between two curves","Horizontal areas between curves","Area between curves that intersect at more than two points (calculator-active)","Volumes with cross sections: squares and rectangles (intro)","Volumes with cross sections: squares and rectangles","Volumes with cross sections: triangles and semicircles","Disc method: revolving around x- or y-axis","Disc method: revolving around other axes","Washer method: revolving around x- or y-axis","Washer method: revolving around other axes","Arc length","Contextual and analytical applications of integration (calculator-active)"]},
  {name:"Parametric equations, polar coordinates, and vector-valued functions",topics:["Parametric equations differentiation","Second derivatives (parametric functions)","Parametric curve arc length","Vector-valued functions differentiation","Second derivatives (vector-valued functions)","Planar motion (differential calc)","Motion along a curve (differential calc)","Planar motion (with integrals)","Differentiate polar functions","Tangents to polar curves","Area bounded by polar curves intro","Area bounded by polar curves","Area between two polar curves","Area with polar functions (calculator-active)"]},
  {name:"Infinite sequences and series",topics:["Sequence convergence/divergence","Partial sums intro","Partial sums & series","Infinite geometric series","nth term test","Integral test","p-series","Direct comparison test","Limit comparison test","Alternating series test","Ratio test","Determine absolute or conditional convergence","Alternating series remainder","Taylor & Maclaurin polynomials","Lagrange error bound","Interval of convergence","Function as a geometric series","Maclaurin series of sin(x), cos(x), and e^x","Integrate & differentiate power series","Integrals & derivatives of functions with known power series"]},
];

/* ── Grade 12+ 심화선택: AP Statistics (Khan Academy) ── */
const APSTAT=[
  {name:"Exploring categorical data",topics:["Individuals, variables, and categorical & quantitative data","Read bar graphs","Read two-way frequency tables","Create two-way frequency tables","Analyze two-way frequency tables","Interpret two-way tables","Mosaic plots","Identify marginal and conditional distributions","Marginal distributions","Conditional distributions"]},
  {name:"Exploring one-variable quantitative data: Displaying and describing",topics:["Reading dot plots & frequency tables","Create histograms","Read histograms","Reading stem and leaf plots","Shape of distributions","Describing distributions","Comparing distributions"]},
  {name:"Exploring one-variable quantitative data: Summary statistics",topics:["Calculating mean and median from data displays","Missing value given the mean","Effects of shifting, adding, & removing a data point","Estimating mean and median in data displays","Interquartile range (IQR)","Sample standard deviation","Visually assess standard deviation","Transforming data","Reading box plots","Interpreting quartiles","Identifying outliers"]},
  {name:"Exploring one-variable quantitative data: Percentiles, z-scores, and the normal distribution",topics:["Calculate percentiles","Calculating z-scores","Comparing with z-scores","Empirical rule","Normal distribution: Area above or below a point","Normal distribution: Area between two points","Normal calculations in reverse"]},
  {name:"Exploring two-variable quantitative data",topics:["Making appropriate scatter plots","Positive and negative linear associations from scatter plots","Describing trends in scatterplots","Describing scatterplots","Correlation coefficient intuition","Calculate and interpret residuals","Residual plots","Calculating the equation of the least-squares line","Interpreting slope and y-intercept for linear models","Using least-squares regression output","Effects of influential points","Identify influential points","Predict with transformed data"]},
  {name:"Collecting data",topics:["Identify the population and sample","Generalizability of results","Types of studies","Bias in samples and surveys","Simple random samples","Sampling methods","Sampling method considerations","Experiment designs","Experiment design considerations","Conclusions in observational studies versus experiments","Finding errors in study conclusions"]},
  {name:"Probability",topics:["Interpret results of simulations","Two-way tables, Venn diagrams, and probability","Calculate conditional probability","Probability with general multiplication rule","Probability of \"at least one\" success"]},
  {name:"Random variables and probability distributions",topics:["Graph probability distributions","Probability with discrete random variables","Develop probability distributions: Theoretical probabilities","Mean (expected value) of a discrete random variable","Interpret expected value","Standard deviation of a discrete random variable","Transforming random variables","Combining random variables","Combining normal random variables","Identifying binomial variables","Binomial probability formula","Calculating binomial probability","Mean and standard deviation of a binomial random variable","Binomial vs. geometric random variables","Geometric distributions","Geometric probability","Cumulative geometric probability"]},
  {name:"Sampling distributions",topics:["Probability in normal density curves","Sample means and the central limit theorem","Biased and unbiased estimators","The normal condition for sample proportions","Mean and standard deviation of sample proportions","Finding probabilities with sample proportions","Mean and standard deviation of difference of sample proportions","Shape of sampling distributions for differences in sample proportions","Mean and standard deviation of sample means","Finding probabilities with sample means","Mean and standard deviation of difference of sample means","Shape of sampling distributions for differences in sample means"]},
  {name:"Inference for categorical data: Proportions",topics:["Conditions for a z interval for a proportion","Finding the critical value z* for a desired confidence level","Calculating a z interval for a proportion","Sample size and margin of error in a z interval for p","Writing null and alternative hypotheses","Estimating P-values from simulations","Writing hypotheses for a test about a proportion","Conditions for a z test about a proportion","Calculating the test statistic in a z test for a proportion","Calculating the P-value in a z test for a proportion","Making conclusions in a z test for a proportion","Type I vs Type II error","Error probabilities and power","Conditions for inference on two proportions","Two-sample z interval for the difference of proportions","Writing hypotheses for testing the difference of proportions","Test statistic in a two-sample z test for the difference of proportions","P-value in a two-sample z test for the difference of proportions","Making conclusions about the difference of proportions"]},
];

/* ── 트랙(학년) → 과목 ──
   Grade 8~11: 학년별 필수 1과목 / Grade 12+: 심화선택 6과목(택1 이상) */
const LEVELS_US=[
  {level:"Grade 8",levelId:"g8",subjects:[
    {id:"prealg",name:"Pre-Algebra",chapters:PREALG},
  ]},
  {level:"Grade 9",levelId:"g9",subjects:[
    {id:"alg1",name:"Algebra 1",chapters:ALG1},
  ]},
  {level:"Grade 10",levelId:"g10",subjects:[
    {id:"geom",name:"Geometry",chapters:GEOM},
  ]},
  {level:"Grade 11",levelId:"g11",subjects:[
    {id:"alg2",name:"Algebra 2",chapters:ALG2},
  ]},
  {level:"Grade 12+ / Advanced",levelId:"g12plus",subjects:[
    {id:"precalc",name:"Pre-calculus",chapters:PRECALC},
    {id:"statprob",name:"Statistics & Probability",chapters:STATPROB},
    {id:"colalg",name:"College Algebra",chapters:COLALG},
    {id:"apcalc_ab",name:"AP Calculus AB",chapters:APCALC_AB},
    {id:"apcalc_bc",name:"AP Calculus BC",chapters:APCALC_BC},
    {id:"apstat",name:"AP Statistics",chapters:APSTAT},
  ]},
];

/* ── 호환용: 옛 Academy 형식 (units = 대단원 이름 배열) ── */
const CURRICULUM_US=LEVELS_US.map(lv=>({level:lv.level,subjects:lv.subjects.map(s=>({id:s.id,name:s.name,units:s.chapters.map(c=>c.name)}))}));

/* 과목 찾기 헬퍼 */
function findSubjectUS(id){for(const lv of LEVELS_US)for(const s of lv.subjects)if(s.id===id)return s;return null;}

export { LEVELS_US, CURRICULUM_US, findSubjectUS };
